### PR TITLE
Feature/react testing library

### PR DESCRIPTION
**Pull request by thawkin3**
I've replaced the existing unit test infrastructure with React Testing Library. 🎉 

This is an industry standard testing library and is perfect for verifying the behavior of this project without having to mock a ton of stuff like was previously being done.

I increased the coverage as well and have tested everything that can reasonably be tested, so it's very near to 100% code coverage.

Closes https://github.com/focus-trap/focus-trap-react/issues/213

All new dependencies I introduced are `devDependencies`:
- `@testing-library/jest-dom` (Core piece of the testing library)
- `@testing-library/react` (For React)
- `@testing-library/user-event` (For triggering tab events)
- `jest-watch-typeahead` (Just for fun and for making choosing files when running Jest in watch mode easier)
- `regenerator-runtime` (For using `async/await` in test files)

Feast your eyes upon this beautiful code coverage report:

Screen Shot 2020-12-18 at 11 49 10 PM

<details>
<summary>PR Checklist</summary>
<br/>

__Please leave this checklist in your PR.__

- [x] Issue being fixed is referenced.
- [x] Source changes maintain:
  - Stated browser compatibility.
  - Stated React compatibility.
- [x] Unit test coverage added/updated.
- ~E2E test coverage added/updated.~
- ~Prop-types added/updated.~
- ~Typings added/updated.~
- ~README updated (API changes, instructions, etc.).~
- [x] Changes to dependencies explained.
- ~Changeset added (run `yarn changeset` locally to add one, and follow the prompts).~
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

</details>

### CODE REVIEW

**Comment by thawkin3** [comment]
@all-contributors please add @thawkin3 for tests

**Comment by cgood92** [comment]
P.s. Another contribution from Workfront!

**Review by stefcameron — APPROVED** [review]
@thawkin3 WOW! I'm impressed.

> Feast your eyes upon this beautiful code coverage report

Indeed! 😍

This was a lot of hard work. Thank you! And I appreciate the extent to which you went to get the coverage to like 99.99%. That "pausable focus trap" test is quite an extensive one.

I'm really happy to have this code base move to RTL. I use it every day at work. Hands down the best front end testing library out there, IMO. And its `user-event` add-on is really cool. Many things are possible now in unit and integration tests that once required Cypress, Silk, or other tools. I just wish `js-dom` had better support for focus handling, but even with its minimal support, you've managed write some good tests!

Some day, it would be great to see the DOM Testing Library used on `focus-trap` where we only have Cypress coverage at the moment. Even `tabbable` could use it.

I'm going to setup the Codecov bot now on this repo to help hold the coverage line (precedent) you've set for future changes.

**Comment by stefcameron** [comment]
> P.s. Another contribution from Workfront!

Nice! Thanks to both of you, and also thanks to Workfront for supporting this project with time and people. Much appreciated.

**Comment by thawkin3** [comment]
> @thawkin3 WOW! I'm impressed.

@stefcameron Haha thanks!

> Some day, it would be great to see the DOM Testing Library used on `focus-trap` where we only have Cypress coverage at the moment. Even `tabbable` could use it.

Agreed. This _might_ be my next initiative when I have some more free time. :wink:

> I'm going to setup the Codecov bot now on this repo to help hold the coverage line (precedent) you've set for future changes.

Please do! I was going to suggest that next, so I'm glad you're on top of it.

**Comment by stefcameron** [comment]
`codecov` bot has been added! 🎉

**Comment by thawkin3** [comment]
Awww yeahhh!

**Pull request merged**
