### PR TITLE
Remove call for maintainers

### LINKED ISSUE #48: Seeking co-maintainers!
I've been shifting my focus away from UI development, so don't plan on addressing new issues myself. If you use this library and want to see development continue, you can make that happen by becoming a co-maintainer — with permissions to triage issues, merge PRs, cut releases, etc.

Please comment below if you're interested!

Another possibility is for a dedicated owner to fork this code and create a new package. I'd be happy to link to that library from the README of this one.

### PR DESCRIPTION
**Pull request by stefcameron**
Fixes #48 now that we're 2 maintainers taking over. Based on the
amount of activity and the stability of the code base, I think we
should be good for a bit.

### CODE REVIEW

**Comment by stefcameron** [comment]
> Merging this PR will not cause any packages to be released. If these changes should not cause updates to packages in this repo, this is fine 🙂

I don't think this is something that warrants publishing. It'll eventually get published, but doesn't warrant a patch in and of itself.

**Comment by stefcameron** [comment]
@maraisr OK with this?

I was also thinking it would make sense to bring `tabbable` and `focus-trap` into this org since they're "part of the family". We can keep their calls for maintainers open. But it would at least give us the ability to do things there as well, since I think #86 should really be fixed there instead of here.

**Comment by maraisr** [comment]
Hi @stefcameron  yeah man. Think we good now. Ill ripple the changeset stuff into those other 2 repo's also. Ill see if we can monorepo them too.

With respects to changeset, yeah that bot is just reminding you that this PR won't release anything.

That being said though, maybe we can stage push up a patch to get the readme to also update within NPM? Or do we wait for a few more features/fixes to land?

**Comment by stefcameron** [comment]
@maraisr I like the idea of adding Changesets to those two other repos! I see David moved them over earlier today, so you should be able to set that up now.

That's true about the README in NPM. Perhaps that warrants a patch. Would be a good excuse for me to see what the full Changesets process is like, so I'll add a Changeset to this PR before I merge it so we can do a patch!

**Comment by stefcameron** [comment]
I'm open to monorepo for the 3 of them as well, but fine to leave them as-is too. Whatever is simplest.

**Comment by stefcameron** [comment]
@maraisr Changeset added!

**Comment by stefcameron** [comment]
I assume we're good to go here. Merging.

**Pull request merged**
