### PR TITLE
Introduces changesets for release management

### PR DESCRIPTION
**Pull request by maraisr**
This PR adds support for https://github.com/atlassian/changesets for our release management as well as introduces running our tests, and lints as an action.

---

@davidtheclark can you please add a `NPM_TOKEN` secret to the repo so github can release this?
@davidtheclark can you also please install the https://github.com/apps/changeset-bot to the repo

### CODE REVIEW

**Comment by stefcameron** [comment]
@maraisr Wow! I'll check this out first thing tomorrow. With this, who would have the permission to publish?

**Comment by maraisr** [comment]
@stefcameron anyone with merge rights. So the flow is:

- developer (internal or external) raises a feature PR. Locally, they'd run `yarn changeset add` which adds a markdown file to the PR, giving us the intention that this change should be documented in a release. Or dont add one, which is for stuff like ci changes etc.
- On a successful merge to master, we have another action that runs, that if it finds any changeset files it'll raise/update a versioning pr. 
- Then its up to whoever has merge rights to master to merge that versioning pr.
- The versioning pr is the one that bumps the npm version string to whatever it resolved through changesets, and allows us to collect a few PR's before we release.
- If this hits master, and its resolved npm version doesnt exist on npm, itll attempt a release. 
- If this is successful; the action will create a changelog.md file, as well as create these notes in github releases.

---

The only outstanding effort from this is for @davidtheclark to either add me as a publisher (npm: marais) and make me admin so I can add an `NPM_TOKEN` secret to the repo. Or he can just ad that secret. Whatever is easier. And secondly, to install the changesets bot to the repo (this'll pop a comment on the PR if a developer forgot to add a changeset, and shows them how to do it.)

**Comment by davidtheclark** [comment]
Other maintainers should be able to grant GitHub and npm access, I believe. Let me know if not.

**Comment by stefcameron** [comment]
> Other maintainers should be able to grant GitHub and npm access, I believe. Let me know if not.

@davidtheclark I was able to invite @maraisr to NPM. With that, I assume either @maraisr or I can generate an NPM token, but then I don't think either of us has enough permissions on this repo to manage Action Secrets. I have yet to use GH Actions, but clicking around in there, I don't see where I could set a secret, and I don't have access to the repo's `Settings` page. I think one of us needs Admin access for that. I'll also guess that only an Admin can invite the Changesets bot to this repo.

@maraisr We should add a status badge for the CI job to the README while we're at it, and remove the Travis one:
image

**Comment by stefcameron** [comment]
@maraisr This is a great explanation of what to expect for other maintainers (if any) and for me to refer to. What do you think about capturing this into a `PUBLISHING.md` file for posterity?
> 
> * developer (internal or external) raises a feature PR. Locally, they'd run `yarn changeset add` which adds a markdown file to the PR, giving us the intention that this change should be documented in a release. Or dont add one, which is for stuff like ci changes etc.
> * On a successful merge to master, we have another action that runs, that if it finds any changeset files it'll raise/update a versioning pr.
> * Then its up to whoever has merge rights to master to merge that versioning pr.
> * The versioning pr is the one that bumps the npm version string to whatever it resolved through changesets, and allows us to collect a few PR's before we release.

About the versioning PR that's auto-opened. I assume it's the bot that does this. If we want to add a few more PRs before we publish, do we just close that versioning PR and let the bot open a new one when another PR gets merged?

> * If this hits master, and its resolved npm version doesnt exist on npm, itll attempt a release.
> * If this is successful; the action will create a changelog.md file, as well as create these notes in github releases.
>

**Comment by maraisr** [comment]
@stefcameron / @davidtheclark I don't think I have npm access, I cannot see this. And yeah we'd need admin access to this repo to add that secret, which is why I was hoping @davidtheclark  you could just assist us with thata?

Re the status badge @stefcameron, I have done this.

Re Publishing.md, I think its probably better suited to a contributing md. Which we could do as part of a subsequent PR. The bot does a pretty good job at explaining what needs to happen next in the pr (which we need admin access for as well to install that)

Re the versioning PR, no. Each change to master just merges the changes into this pr. So it can just stay open till we're comfortable with a release.

**Comment by stefcameron** [comment]
> @stefcameron / @davidtheclark I don't think I have npm access, I cannot see this. And yeah we'd need admin access to this repo to add that secret, which is why I was hoping @davidtheclark you could just assist us with thata?

🤔 I did go into NPM this morning and invited user `marais`. Did you not get an invite to join? In my experience, you have to accept the invite before you can see you have access.

> Re the status badge @stefcameron, I have done this.

Thanks!

> Re Publishing.md, I think its probably better suited to a contributing md. Which we could do as part of a subsequent PR. The bot does a pretty good job at explaining what needs to happen next in the pr (which we need admin access for as well to install that)

Contributing.md makes sense, but if the bot does a good job, perhaps it's not needed. You obviously have more experience than me with changesets (I've never used it before).

> Re the versioning PR, no. Each change to master just merges the changes into this pr. So it can just stay open till we're comfortable with a release.

OK, thanks for explaining that!

I guess it's stuff like that I would put in the Contributing.md, unless the bot also explains that. Or maybe it's somewhere in their docs (I read them a few weeks ago when I came across Changesets in another repo and got curious, but don't remember all the details). Still, for someone totally new to it like myself, having a short list of what to expect and how to work with it could be helpful.

**Comment by stefcameron** [comment]
> Thanks for also changing over to `yarn`! All looks good to me now.

Of course, we still need that NPM_TOKEN setup, and the bot access to the repo before merging.

**Comment by davidtheclark** [comment]
If you'd like to incorporate a tool that involves such integrations, I'd suggest forking the repository. I'd rather not manage secrets or GitHub apps.

**Comment by maraisr** [comment]
@stefcameron what do you think about forking then potentially? @davidtheclark  would you be open to a PR to point people at a fork?

**Comment by davidtheclark** [comment]
> @davidtheclark would you be open to a PR to point people at a fork?

👍 Definitely.

**Comment by stefcameron** [comment]
> @stefcameron what do you think about forking then potentially?

Adding Changesets is interesting, but I don't think it warrants forking. I'm still too new to the repo to know if it will really see enough "action" to really need Changesets. I'm all for it, but it doesn't seem to justify forking, IMO.

Even if we fork for this, won't we still have the issue of not being able to publish under the `focus-trap-react` package name? We won't be able to do that unless @davidtheclark adds (and manages) an additional publish token in his NPM account with the current permissions. So we'd be forced to publish under a different name.

Because the repo went unmaintained for about a year, there were subsequently a lot of forks and probably a lot of alternate published packages to fix one issue or another. My initial interest to help with this repo wasn't to add to this, but rather to help with the original repo and original package name I came to find a few months ago and found so useful.

**Comment by maraisr** [comment]
Changesets just means no 1 person manages the releasing, but rather the system. So its actually less work. Like we merge a PR through the GH app, wait the 3 mins for the CI to run, and then merge the versioning PR through the app as well. So no logging into GH, cloning the changes, building and then publishing all manually. So there is HUGE benefits there. 

In terms of tokens and bots etc... This is something that I can personally manage for us, just need _admin_ rights to be able to do it. Which if @davidtheclark  is happy to do, if he gives me npm publish rights—we can fork this repo into another space where we do have this level of right, and still publish to the same package on npm. Either that, or @davidtheclark  just "move" the repo to another place also (rather than fork).

Either way; @davidtheclark. @stefcameron and I are wanting to help, you don't have the time to help us with releases and such, and we're not sure on the level of involvement from you in this. So we just trying to help smoothen the workload. If it was merely to look at issues, and merge PR's we're still happy to do that :)

**Comment by davidtheclark** [comment]
> if he gives me npm publish rights

@maraisr Done.

> Either that, or @davidtheclark just "move" the repo to another place also (rather than fork).

Happy to.

> we're not sure on the level of involvement from you in this

I would love to hand off this project completely, as I am not working in this space right now.

**Comment by stefcameron** [comment]
> > Either that, or @davidtheclark just "move" the repo to another place also (rather than fork).
> 
> Happy to.
> 
> > we're not sure on the level of involvement from you in this
> 
> I would love to hand off this project completely, as I am not working in this space right now.

@maraisr Moving the repo sounds like a good option to me. Do you already have a location in mind?

**Comment by maraisr** [comment]
We can move it to your personal GitHub perhaps @stefcameron, im happy to have it moved to mine as well if you're not comfortable with that! 

@davidtheclark thank you so much for working with us on this!

**Comment by stefcameron** [comment]
@maraisr @davidtheclark Actually, I just had a thought. Looking at the bigger picture, David has the following repos to hand-off, and they're all related:
- focus-trap-react
- focus-trap
- tabbable

I'm not committing to maintaining them all at this time, but would it make sense to move all 3 to a new `focus-trap` org?

**Comment by maraisr** [comment]
I do like that idea, seeing as they all work together anyway! I'll be at my PC in a min, I or you can create that!

But! And this is maybe jumping the gun a bit. I'm also a monorepo fan, which means I'd ultimately like to have it in one place.

**Comment by stefcameron** [comment]
> I do like that idea, seeing as they all work together anyway! I'll be at my PC in a min, I or you can create that!
> 

Cool, I just created the `focus-trap` org and you should have an invite to it. I've never moved a repo between orgs, so I'm not sure what steps @davidtheclark would have to follow, and if he needs to be a member in that org.

> But! And this is maybe jumping the gun a bit. I'm also a monorepo fan, which means I'd ultimately like to have it in one place.

I like monorepos as well, especially for related packages, but let's start with moving this repo over, and if David wants to, we can move the other 2 (though I'm not signing up to maintain them...). We could eventually converge them to a single monorepo, perhaps into `focus-trap/focus-trap`.

**Comment by maraisr** [comment]
WoW, thanks for that @stefcameron! Yeah @davidtheclark  would need ot be part of it too, and of admin rights. Then all @davidtheclark  would need to do is, go into the settings of this repo go down to the danger section, and click "move". 

Re the maintenance, yeah I think initially lets just get it all under the same roof (the org), iron out any kinks and take it from there. Id be happy to give it a few hours a week in maintenance.

**Comment by maraisr** [comment]
also @stefcameron can you make me an owner of focus-trap also? :)

**Comment by stefcameron** [comment]
> WoW, thanks for that @stefcameron!

My pleasure!

> Yeah @davidtheclark would need ot be part of it too, and of admin rights.

Done, invited as owner.

> Re the maintenance, yeah I think initially lets just get it all under the same roof (the org), iron out any kinks and take it from there.

Sounds good!

> also @stefcameron can you make me an owner of focus-trap also? :)

Done!

**Comment by maraisr** [comment]
@stefcameron I have setup the GH bot for changesets, and added in a npm token for the releases. We can merge this one when ready

**Comment by stefcameron** [comment]
> @stefcameron I have setup the GH bot for changesets, and added in a npm token for the releases. We can merge this one when ready

@maraisr Thanks for setting that up! I'm good with merging it now. I'll give you the honors!

After this, I was thinking of setting-up `master` branch protection rules like this:
image

LMK if you're good with that and I'll get it done.

**Pull request merged**
