### PR TITLE
chore: adds a format:watch script for running Prettier in watch mode

### PR DESCRIPTION
**Pull request by thawkin3**
This adds a `format:watch` script to `package.json` for running Prettier in watch mode. It's useful for local development to let Prettier format your code as you go rather than having to manually run it.

It uses the `onchange` package to watch for changes, so I've added that as a `devDependency` for this project.

I did add a changeset for this since it looks like other tooling changes have included a changeset, but I can remove it if it's not wanted for these kinds of MRs.

### Tooling

- [ ] ~Issue being fixed is referenced.~
- [x] Changes to dependencies explained.
- [ ] ~README instructions updated.~
- [ ] ~A Changeset is __not__ added.~

👉 If any of these don't apply, please ~cross them out~.

### CODE REVIEW

**Comment by stefcameron** [comment]
Nice! Thanks for your contribution, @thawkin3 !

> I did add a changeset for this since it looks like other tooling changes have included a changeset, but I can remove it if it's not wanted for these kinds of MRs.

Typically we keep changesets for changes that will affect consumers of the package, so it's not needed here. I'll just delete it before I merge your PR. Thanks for adding it just in case. 🙂 

@all-contributors add @thawkin3 for infra

**Review by stefcameron — APPROVED** [review]

**Comment by stefcameron** [comment]
@all-contributors add @thawkin3 for infra

**Comment by thawkin3** [comment]
Thanks @stefcameron! I appreciate your responsiveness in getting this merged so quickly. I'll have more contributions soon to come!

**Comment by stefcameron** [comment]
My pleasure!

**Pull request merged**
